### ISSUE TITLE
addEvent is not defined

### ISSUE THREAD

**Issue by joaquin-becerra** [decidir/sdk-javascript-v2#1]
Siguiendo el ejemplo del 

https://github.com/decidir/sdk-javascript-v2/blob/master/README.md

Tengo un error al ejecutar el siguiente código 

`//Asigna la funcion de invocacion al evento de submit del formulario
addEvent(form,'submit',sendForm));`

El error en consola del navegador es 

`addEvent is not defined`

Estoy incluyendo antes el siguiente script

`https://live.decidir.com/static/v1/decidir.js`

Esta funcion deberia estar definida en ese script? 
Es responsabilidad del desarrollador enlazar el submit del  formulario a la funcion sendForm?

**Comment by ignaciovalek** [comment]
Hola Joaquín, la skd define al objeto Decidir para la comunicación. Al invocar a la función createToken del mismo, debes pasar como argumentos tu formulario obtenido del DOM y una función de callback para procesar la respuesta.
Aguardo tus comentarios. 

Saludos!

Ignacio

**Comment by ignaciovalek** [comment]
No te contesté tu pregunta. La invocación de addEvent en la documentación es para mostrar el vínculo entre el submit del formulario y la invocación de la funcion createToken del objeto Decidir.
La manera de enlazar el formulario con la sdk queda a criterio del desarrollador.

Saludos!

Ignacio

**Comment by joaquin-becerra** [comment]
Bien!, entonces con algo asi alcanzaria no?

`<- form action="noaction" method="POST"  onsubmit="sendForm(this);return false;"->
...
-/form-

<-script type="text/javascript"->
(...)
//funcion de invocacion con sdk
function sendForm(form) {
  decidir.createToken(form, sdkResponseHandler);//formulario y callback
  return false;
}
<-/script->
`

Saludos

**Comment by juliangorge** [comment]
Revisa el ID del formulario, no lo está encontrando. Ej:

`<form id="billingForm" method="post" name="billingForm"> .....`

`document.querySelector('#billingForm');`

**Comment by ebalmaceda** [comment]
Es una pregunta vieja, pero vi que sigue el problema en el ejemplo de la documentacion. 
Hay que cambiar la linea:
addEvent(form,'submit',sendForm));

Por:
form.addEventListener('submit',sendForm);
