### ISSUE TITLE
Publicar sdk en npm para uso via package managers y implementar semantic versioning

### ISSUE THREAD

**Issue by devarg** [decidir/sdk-javascript-v2#4]
Para usar la librería en la escena enterprise donde muchas veces se usa como thirdparty integrado a una solución, sería importante que sea publicada en NPM para poder integrarla mas simplemente en projectos no solo JS sino Typescript. Por otro lado sería ideal que salga modularizada (o se provea una versión umd) para poder generar typings y no tener que mandarla al global scope donde carga actualmente, lo que también dificulta el automated testing. Otra sugerencia sería que si la mantienen en el cdn que le agreguen integrity checks.

Son simplemente sugerencias surgidas de la implementación que mejorarían la integración, seguridad y previsibilidad de errores productivos.

Desde ya muchas gracias

**Comment by mmansilla-prisma** [comment]
Buenas tardes @devarg, estamos trabajando en actualizar y crear mas sdks front-end como comentas, cuando tengamos las nuevas versiones relanzaremos nuestras sdk´s.

Saludos
