### ISSUE TITLE
Obtener payment_method_id

### ISSUE THREAD

**Issue by jbiancovns** [decidir/sdk-javascript-v2#6]
Hola chicos, les hago una pregunta:

1) Hay alguna forma de obtener el payment_method_id directamente desde el SDK de javascript? la funcion decidir.cardType(cardNumber) retorna un string como por ejemplo "Visa".

El backend necesita el ID, podria hacer un array asociativo con todos los posibles ID's y sus strings .. pero estimo que debe haber alguna manera mas sencilla.

Saludos

**Comment by jbiancovns** [comment]
Listo chicos, ya lo solucione. Gracias

**Comment by jbiancovns** [comment]
Chicos, modifique el issue, y solo tengo esa duda, si me pueden dar una mano se los agradeceria.

Saludos

**Comment by franciscomemoli** [comment]
Hola Tengo el mismo problema, lo pudiste solucionar de alguna forma?

**Comment by juliangorge** [comment]
> Hola Tengo el mismo problema, lo pudiste solucionar de alguna forma?

Hola pudiste hacerlo?

**Comment by mmansilla-prisma** [comment]
Buenas tardes @juliangorge @franciscomemoli  @jbiancovns, les comento que mediante la sdk no hay forma hoy de obtener el id de medios de pago, así mismo le dejo la documentación para que puedan obtenerlo mediante la API REST https://decidirv2.api-docs.io/1.0/tablas-de-referencia-e-informacion-para-el-implementador/obtener-todos-medios-pago

Dejo esta mejora cargada para que pronto la incluyamos en la sdk.

Saludos!

**Comment by Juanse-Gimenez** [comment]
> Buenas tardes @juliangorge @franciscomemoli @jbiancovns, les comento que mediante la sdk no hay forma hoy de obtener el id de medios de pago, así mismo le dejo la documentación para que puedan obtenerlo mediante la API REST https://decidirv2.api-docs.io/1.0/tablas-de-referencia-e-informacion-para-el-implementador/obtener-todos-medios-pago
> 
> Dejo esta mejora cargada para que pronto la incluyamos en la sdk.
> 
> Saludos!

Hola buen dia, hay algun sdk o alguna tool para identificar el tipo de tarjeta(visa,master,cabal, etc) y si es debito o credito? Estoy realizando una integracion pero no veo forma de conseguir estos datos

**Comment by vaneemvg** [comment]
Buenas tardes, entiendo que el sdk no responde el id del metodo de pago, pero tengo la duda de como hacer para reconocer el mismo?, ya que por ejemplo la api rest me informa 3 id de medio de pago distintos para una tarjeta American Express
`[
   
    {
        "idmediopago": "6",
        "descripcion": " ",
        "moneda": "Pesos ARA",
        "tarjeta": "American Express"
    },
    ...
    
    {
        "idmediopago": "111",
        "descripcion": "Amex Prisma",
        "moneda": "Pesos ARA",
        "tarjeta": "Amex Prisma"
    },
    ...
     {
        "idmediopago": "65",
        "descripcion": "Amex",
        "moneda": "Pesos ARA",
        "tarjeta": "Amex"
    },
   
]`
el sdk de js solo reconoce, mediante expresión regular del bin, que es Amex. Qué id debo enviar? probé con los 3 y en todos los casos me retorna _invalid_param: payment_method_id_
Desde ya agradezco alquien pueda ayudarme.

**Comment by juliangorge** [comment]
Yo ocupo

> Buenas tardes, entiendo que el sdk no responde el id del metodo de pago, pero tengo la duda de como hacer para reconocer el mismo?, ya que por ejemplo la api rest me informa 3 id de medio de pago distintos para una tarjeta American Express `[
> 
> ```
> {
>     "idmediopago": "6",
>     "descripcion": " ",
>     "moneda": "Pesos ARA",
>     "tarjeta": "American Express"
> },
> ...
> 
> {
>     "idmediopago": "111",
>     "descripcion": "Amex Prisma",
>     "moneda": "Pesos ARA",
>     "tarjeta": "Amex Prisma"
> },
> ...
>  {
>     "idmediopago": "65",
>     "descripcion": "Amex",
>     "moneda": "Pesos ARA",
>     "tarjeta": "Amex"
> },
> ```
> 
> ]` el sdk de js solo reconoce, mediante expresión regular del bin, que es Amex. Qué id debo enviar? probé con los 3 y en todos los casos me retorna _invalid_param: payment_method_id_ Desde ya agradezco alquien pueda ayudarme.

Yo ocupo 111 como entero. Pero ya no uso el sdk de javascript, sólo el de PHP

**Comment by vaneemvg** [comment]
> no uso el sdk de javascript, sólo el de PHP

Gracias por la respuesta, el 111 también me retornó error. Lamentablemente tengo mi sitio en python y js :-(
