### ISSUE TITLE
Obtener listas de tarjetas tokenizadas

### ISSUE THREAD

**Issue by Marequena** [decidir/sdk-javascript-v2#7]
Puedo mediante decidir obtener las tarjetas tokenizadas?

**Comment by mmansilla-prisma** [comment]
Buenas tardes @Marequena, 
Si se puede obtener las tarjetas tokenizadas, pero no por vía de esta sdk de javascript, te recomiendo usar alguna sdk decidir de backend ej:
- https://github.com/decidir/sdk-java-v2#listadotarjetastokenizadas
- https://github.com/decidir/sdk-php-v2#listadotarjetastokenizadas
- https://github.com/decidir/sdk-.net-v2#listadotarjetastokenizadas
- https://github.com/decidir/sdk-nodejs-v2#listadotarjetastokenizadas
O bien consultarlas vía APIREST https://decidirv2.api-docs.io/1.0/tokenizacion-de-tarjetas/listado-de-tarjetas-tokenizadas

Saludos
