### ISSUE TITLE
Como se obtienen las cuotas al pagar con tarjeta de credito?

### ISSUE THREAD

**Issue by ebalmaceda** [decidir/sdk-javascript-v2#9]
Estoy perdido y creo que estoy planteando mal el problema.
No entiendo como obtengo las cuotas de cada tarjeta de credito (las installments).

Yo imaginaba que selecciona una tarjeta y ahi podria mostrar las cuotas disponibles que ofrece es tarjeta con sus intereses y demas.

¿Como funciona esto? Gracias!

**Comment by mmansilla-prisma** [comment]
Buenas tardes @ebalmaceda, te recomiendo que leas dentro del README del proyecto el flujo para generar un token y luego necesitar ir por cualquiera de las sdk para backend para seguir con el procesamiento de pago.

Y comentas no hay forma de obtener las cuotas de cada tarjeta de crédito, installments es el dato que envías al momento de procesar el pago.

Sino como alternativa existe la documentación de nuestra API REST la cual comprende toda la información sobre los flujos
https://decidirv2.api-docs.io/1.0/guia-de-inicio

**Comment by ebalmaceda** [comment]
hola! Gracias por tu respuesta. Dejo este comentario porque quizas alguien esta en el mismo punto que yo y no sabe como continuar y yo ya pude resolver mi "problema".

Creo que no se entendio mi pregunta, porque lo que estaba errado en mi era el rasonamiento.

A grandes rasgos para generar el pago tenes que mandar, por ejemplo, por la API REST, el monto a pagar, las cuotas y los datos de la tarjeta de credito.

Lo que yo no entendia era como sabia los intereses de cada tarjeta / banco y cuota seleccionada y pensaba que eso me lo informaba prisma. Me explicaron dos colegas programadores que NO ES ASI.

Por detras de esto debe hacerse un panel de control o alguna interface donde el administrador del sitio ecommerce (el vendedor) pueda poner TARJETA VISA - BANCO NACION - 6 CUOTAS = 10% de interes.
Este interes se suma al monto de la venta y ahi si se envia a la API REST las 6 cuotas, el monto mas el interes y los datos de la tarjeta.

Por supuesto que esa relacion cuota - banco -interes  tiene que ser exactamente la misma que el comerciante tiene pactada con su banco, porque sino tendra que hacerse cargo del interes, la responsabilidad cae sobre el comerciante.

La duda me surgio porque yo habia trabajando con la api de MercadoPago y esta me devolvia las tarjetas disponibles para pagar, con las cuotas y el interes de cada cuota.

Ahora entiendo que Prisma no funciona asi, sino que tenemos libertar de procesar las cuotas como queramos, por supuesto que luego hay que hacerse cargo de intereses y demas. Hay que ser muy cuidadoso a la hora de configurar esto en el backoficce del ecommerce.

Por favor, corrigime si estoy equivocado.

**Comment by mmansilla-prisma** [comment]
Exactamente, es como comentas, dentro del procesamiento de pago y anteriormente el token no se esta evaluando tema intereses, eso lo tiene que configurar cada comercio.

Saludos

**Comment by ebalmaceda** [comment]
Buenas tardes @mmansilla-prisma, quisiera dejar una ultima consulta que seguro sabras respnderme para ya dejar este tema claro, quizas para todos es una obviedad, pero a mi me trajo dudas.

Como se explico anteriormente, es el comercio (el vendedor) el que debe hacer su lógica de intereses, según la tarjeta y las cuotas seleccionadas por el comprador.

Pero me queda fuera de la ecuación los bancos emisores de tarjetas, obtengo todas las tarjetas de este endpoint:
https://developers.decidir.com/api/v2/payment-methods/{id-moneda}

Ahí mismo están todas las tarjetas de cada banco disponible? O el banco emisor de tarjeta no es necesario al trabajar con Prisma? Para generar el token de pago y ejecutar el mismo claramente NO tengo que enviar el emisor de la tarjeta, pero se que a veces, una tarjeta visa dependiendo del banco emisor tiene un plan de cuotas y otra de otro banco no (aunque también sea visa).

Si esto es asi, no se como obtener el emisor (el banco que la emite) de una tarjeta de credito para aplicar el plan de interes.

Pido disculpas si este no es el lugar para plantear la duda, muchas gracias.

**Comment by LucasGanuza** [comment]
@ebalmaceda Hola! disculpa te hablo despues de años, estoy teniendo la misma cuestion, pudiste resolver en su momento? Gracias!

**Comment by ebalmaceda** [comment]
@LucasGanuza hola! Lamentablemente el desarrollo de ese tiempo no llego a completarse. Terminamos utilizando MercadoPago que nos entregaba automaricamente las cuotas de cada tarjeta, banco emisor y todo.
Si llegas a resolverlo por favor deja tu solucion aqui.
